sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    bucket-name: skytakeout-jx
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    access-key-id: ${OSS_ACCESS_KEY_ID}

